### ISSUE TITLE
Plugin simply doesnt install

### ISSUE THREAD

**Issue by Juan-Paquello** [egg82/AdvancedEnchantments#10]
When I put the .jar into my plugins folder and restart the server nothing happens, nothing new in the console, and the only thing that changes is a folder in the plugins folder that only contains a folder called "External" I've attached the folder it's created.
[AdvancedEnchantments.zip](https://github.com/egg82/AdvancedEnchantments/files/3438581/AdvancedEnchantments.zip)

**Comment by Juan-Paquello** [comment]
Are there any dependencies or steps that I am missing?

**Comment by egg82** [comment]
Delete the "external" folder, re-download the plugin, and wait a bit for it to start up.

Make sure that your server has a constant, reliable connection to the internet. AE downloads libs and checks for library updates on startup.

**Comment by Juan-Paquello** [comment]
I tried and the same thing happened. What do you mean by library updates?

**Comment by Juan-Paquello** [comment]
It wasn't fixed and I've removed and reinstalled multiple times... what am I doing wrong. Would you like to see a server startup log?

**Comment by Juan-Paquello** [comment]
Hey, I found an error. In the console it says this: _[me.egg82.ae.BukkitBootstrap] Could not download file from URLs provided._

What does that mean?

**Comment by egg82** [comment]
Means you don't have a valid, active internet connection from the server. One way or another the requests to download the library files are being blocked. DNS, firewall, other plugins..

**Comment by Juan-Paquello** [comment]
Okay, thanks! Would you know any plugins or settings that may interfere by any chance?

**Comment by egg82** [comment]
If another plugin does interfere, then let me know. Otherwise, none that I know of. Enjoy!

**Comment by dmr612** [comment]
Juan did you manage to fix this? i have the same issue

**Comment by BluLightShow** [comment]
Startup issues were fixed in #12 on authors and so if it's truly something else ¯\_(⊙_ʖ⊙)_/¯

**Comment by Juan-Paquello** [comment]
Unfortunately I wasn’t able to fix the issue. I believe that it’s because of the service that I use to host my server protecting their network.

I ran a server home-hosted and it worked well, so I though I could upload the files to the main server but that didn’t work and it tried to redownload them. Are there any files other than the plugin folder that need to be carried over or does it just check every time?

**Comment by BluLightShow** [comment]
In #12 egg said something about the plugin doing a check Everytime it starts but should be able to run without. Maybe it's related?

**Comment by Juan-Paquello** [comment]
Egg is it possible to disable that or is that necessary?

**Comment by egg82** [comment]
Looks like #10 #11 and #12 are loosely related due to the issues all coming from the same system.

AE downloads and inject dependencies it needs at startup. Additionally, it checks for dependency updates on startup. LuckPerms does this same thing, in fact.

I'll re-open and see if I can figure out an elegant way to handle dep version checking/updating on hosts that don't allow library downloads. In the meantime I'll see if I can talk to some hosts about how they handle this type of thing.

**Comment by egg82** [comment]
The plugin will go to external .xml files to check for new versions of certain libraries, but if they can't be updated it won't try to download them. Either the xml file fetching is being blocked, or for whatever reason the plugin is trying to download/re-download some libraries.

If copying the "external" directory from the plugin's main folder doesn't work, then your host has some VERY strict policies and you should talk to them about that. I understand blocking external jar downloads, but blocking fetching of XML files is a little ridiculous in my opinion.
