### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by dmr612** [egg82/AdvancedEnchantments#11]
I have a Spigot server 14.3, when i installed the jar on the plugin folder and reset the server, the plugin generated a folder inside, but this folder lacks some files like config an so on. It's because the plugin takes some time to load or there's another reason? it's been 20 minutes since installing the .jar

**Comment by BluLightShow** [comment]
This looks similar to #12 as far as long boot times.

**Comment by egg82** [comment]
related to #12 I believe. My apologies for this; it should be fixed now and I'll be submitting some patches later that will resolve any similar issues in the future.

**Comment by dmr612** [comment]
Actually is related to #10
