### ISSUE TITLE
Slow Server Loading Time due to "Fork Checking"

### ISSUE THREAD

**Issue by kagaminecyn** [egg82/AdvancedEnchantments#12]
Please help! The plugin is making my server take half an hour to load up because it's checking for something before booting!

30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.BukkitBootstrap.lambda$buildInject$0(BukkitBootstrap.java:225)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.BukkitBootstrap.buildInjectWait(BukkitBootstrap.java:230)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.external.ninja.egg82.maven.Artifact$Builder.build(Artifact.java:176)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.external.ninja.egg82.maven.Artifact.access$1100(Artifact.java:18)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.external.ninja.egg82.maven.Artifact.build(Artifact.java:217)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.external.ninja.egg82.utils.MavenUtil.getSnapshotVersion(MavenUtil.java:421)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.external.ninja.egg82.utils.DocumentUtil.getDocument(DocumentUtil.java:39)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.external.ninja.egg82.utils.HTTPUtil.getInputStream(HTTPUtil.java:125)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN at me.egg82.ae.external.ninja.egg82.utils.HTTPUtil.getConnection(HTTPUtil.java:94)
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN java.io.IOException: Server returned status code 524
30.07 22:28:07 [Server] ForkJoinPool-2-worker-1/WARN ERROR me.egg82.ae.BukkitBootstrap - Server returned status code 524
30.07 22:26:50 [Server] User Authenticator #1/INFO UUID of player VictoriaPhD is 45d0b795-8d3c-4558-9028-913d1c84ccb1
30.07 22:21:56 [Server] Server thread/INFO §e[§bAdvancedEnchantments§e] §r§eChecking version of §fPacketWrapper
30.07 22:21:56 [Server] Server thread/INFO §e[§bAdvancedEnchantments§e] §r§eChecking version of §fACF
30.07 22:21:56 [Server] Server thread/INFO Loading AdvancedEnchantments v4.14.19

**Comment by BluLightShow** [comment]
I can confirm. I have a similar error to this and it's causing my server's boot to be immensely longer, often freezing the boot entirely:
`31.07 03:06:31 [Server] ERROR [me.egg82.ae.BukkitBootstrap] Server returned status code 524
31.07 03:06:31 [Server] INFO java.io.IOException: Server returned status code 524
31.07 03:06:31 [Server] INFO at me.egg82.ae.external.ninja.egg82.utils.HTTPUtil.getConnection(HTTPUtil.java:94) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.external.ninja.egg82.utils.HTTPUtil.getInputStream(HTTPUtil.java:125) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.external.ninja.egg82.utils.DocumentUtil.getDocument(DocumentUtil.java:39) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.external.ninja.egg82.utils.MavenUtil.getSnapshotVersion(MavenUtil.java:421) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.external.ninja.egg82.maven.Artifact.build(Artifact.java:217) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.external.ninja.egg82.maven.Artifact.access$1100(Artifact.java:18) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.external.ninja.egg82.maven.Artifact$Builder.build(Artifact.java:176) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.BukkitBootstrap.buildInjectWait(BukkitBootstrap.java:230) ~[?:?]
31.07 03:06:31 [Server] INFO at me.egg82.ae.BukkitBootstrap.lambda$buildInject$0(BukkitBootstrap.java:225) ~[?:?]
`

**Comment by egg82** [comment]
This was entirely my fault, and should be resolved now.

The plugin fetches/downloads external libraries on startup. I have it initially fetch from my personal repo, then from the sources my repo proxies (so if my site/repo goes down it still works) - I had a rather rare issue earlier which didn't take the Nexus offline completely, but rather stalled any requests indefinitely. This, in turn, caused the plugins using it to hang.

I've resolved the issue with the service now and it should be working fine (confirmed by myself and a few others using the plugins) and I'll also be resolving similar issues in the plugins themselves in a later update.

Again, I apologize for this. I had monitoring set up for exactly this sort of event some time ago but recently switched to a new monitoring service and hadn't had time to set things up properly again.
