### ISSUE TITLE
Artisan bug

### ISSUE THREAD

**Issue by sinsoffallengods** [egg82/AdvancedEnchantments#15]
Artisan 3 on a diamond pickaxe can be used 13-14 times, seeming to randomize between the two.

Artisan 3 on a diamond pickaxe that already has unbreaking 3, also takes 13-14 times. This appears to mean that unbreaking isn't calculated into it when artisan is involved.

**Comment by egg82** [comment]
Surprisingly enough, this is somewhat intentional. Helps to keep balance since the enchants can be a little OP. If you believe otherwise, let me know!

**Comment by sinsoffallengods** [comment]
If possible I would like it to work where unbreaking makes it last longer.
If you choose to stay with the current course, maybe make it so they are
incompatible with each other? That might make a bit more sense then having
both of them on, but unbreaking being essentially non functioning. Thanks
for working with me on these bugs. I have another one potentially incoming
relating to smelting but I am testing it with users first to make sure it
is actually a bug/problem.

**Comment by egg82** [comment]
Done. Jenkins master should have the new build ready to test.
https://jenkins.egg82.me/job/egg82/job/AdvancedEnchantments/job/master/
