### ISSUE TITLE
Config Option for Soulbound to not require souls

### ISSUE THREAD

**Issue by NightFuryStrike** [egg82/AdvancedEnchantments#16]
Hello, I was wondering if it would be possible to add a config option that would make the soulbound enchantment not require souls and instead always return the soulbound item to the player's inventory if the player dies.

The reason I would like this option is because I wanted to make most legendary items on my server soulbound so players don't have to worry about losing their hard earned legendary items without having to gather souls.

Thanks for reading!

Edit: Posted in Spigot Forums instead

**Comment by egg82** [comment]
This is definitely the best place to open issues - I apologize for not replying in a timely manner.

I've been considering a few different ways to get this idea to work without completely changing the behavior of the plugin and not cluttering up the config. I'll think on it some more and get back to this.

**Comment by egg82** [comment]
Fixed in 57f8300
Latest master available on the Jenkins if you'd like to test: https://jenkins.egg82.me/job/egg82/job/AdvancedEnchantments/job/master/
