### ISSUE TITLE
Items sometimes not loading in chests

### ISSUE THREAD

**Issue by NightFuryStrike** [egg82/AdvancedEnchantments#19]
Plugin version: '4.18.24 (from Jenkins)'
Server type: 'Paper (Build 225).'
Server version: '1.14.4'

**Describe the bug**
After updating to the version you wanted me to test, everything worked exactly as it should (and I can also confirm that using a death chest plugin does not cause any duplication with soulbound items), but for some reason my players started noticing that items in chests would randomly decide to not load until an item is added or removed from the chest. Sometimes only a few items will not show up while other times the chest will appear to be empty. This is very strange behavior and stopped happening when I reverted the plugin back to 4.18.23.

It appears to be a conflict with another plugin, because this does not seem to happen when this plugin (4.18.24) is installed on it's own. I am currently testing on my test server to figure out exactly which plugins are causing this to happen.

**Expected behavior**
All items should appear in chests,

**To Reproduce**
Open chests full of items randomly until something does not load.
(I will comment to let you know which plugins are causing this, still currently in the process of testing)
**Edit: Happens with ProtocolLib installed**

**Screenshots**
(Will add screenshots when done testing)

**Comment by NightFuryStrike** [comment]
Update:
The issue appears to occur with ProtocolLib installed.
No errors appear in console.

To reproduce: 
Install AdvancedEnchantments v4.18.24 and ProtocolLib
Fill a few chests with items, then open  and close them randomly until something doesn't load.

I have attached a video below that shows the problem:
https://1drv.ms/v/s!AknzfCjeCluIoe0fPA2kEpA8GtatKA?e=Qno5Bh

**Comment by egg82** [comment]
Interesting. Perhaps give the [latest master](https://jenkins.egg82.me/job/egg82/job/AdvancedEnchantments/job/master/) a try and enable debug output in the config (reload the plugin with the `/ae reload` command) - see if it's trying to place a fake block (unlikely) or is instead somehow marking the chest as an enchanting table (still unlikely, but more likely)

**Comment by NightFuryStrike** [comment]
Unfortunately while using the latest master build and with debugging enabled, nothing appeared in console whenever the bug happened. Here is a video showing the console while testing in case there is anything else there that could help

https://1drv.ms/v/s!AknzfCjeCluIoe0pxoBBw3R4cU7OFg?e=URSgZq

**Comment by egg82** [comment]
Tested, verified, fixed, verified fix.
Thanks again for the bug report!
