### ISSUE TITLE
error a la hora de poner el encantamiento

### ISSUE THREAD

**Issue by g3ra456** [egg82/AdvancedEnchantments#2]
Los comandos utilizados son estos /ae add Explosive 1 
Lo sigueinte en salir es esto:
I´m sorry, but there was an error performing this command. 

En la consola me aparece este error:  entre mas cosas
24.06 19:31:46  [Servidor]  WARN La tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:46  [Servidor]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8 .0_181]
 24.06 19:31:46  [Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19: 31:46  [Servidor]  INFOat net.minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Server]  INFO at net.minecraft.erver .v1_12_R1.DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Server]  INFO en net.minecraft.server.v1_12_R1.MinecraftServerD (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Servidor]  INFO en org.bukkit.craftbukkcelpack : 353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Servidor]  INFOat org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Servidor]  INFO en mí. egg82.ae.tasks.TaskMagnetic.run (TaskMagnetic.java:36) ~ [?:?]
 24.06 19:31:46  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ) ~ [?:?]
 24.06 19:31:46  [Servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem. <init> (BukkitEnchantableItem.java:33) ~ [?:?]
 24.06 19:31:46  [Servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [?:?]
 24.06 19:31:46  [Servidor] INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:46  [Server]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment. getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:46  [Servidor]  WARN La tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:46  [Servidor]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8 .0_181]
 24.06 19:31:46  [Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19: 31:46  [Servidor]  INFOat net.minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Server]  INFO at net.minecraft.erver .v1_12_R1.DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Server]  INFO en net.minecraft.server.v1_12_R1.MinecraftServerD (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Servidor]  INFO en org.bukkit.craftbukkcelpack : 353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Servidor]  INFOat org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:46  [Servidor]  INFO en mí. egg82.ae.tasks.TaskMagnetic.run (TaskMagnetic.java:36) ~ [?:?]
 24.06 19:31:46  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ) ~ [?:?]
 24.06 19:31:46  [Servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem. <init> (BukkitEnchantableItem.java:33) ~ [?:?]
 24.06 19:31:46  [Servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [?:?]
 24.06 19:31:46  [Servidor] INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:46  [Server]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment. getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:46  [Servidor] La  tarea WARN # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:46  [ Multiactividad ] Se omitieron 138 líneas debido al límite de velocidad (30 / s)
 24.06 19:31:45  [Servidor ]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:45  [Servidor]  WARNLa tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:45  [Server]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8.0_181]
 24.06 19:31:45  [ Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Servidor]  INFO en la red. minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Server]  INFO en net.minecraft.server.v1_12_R1. DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45 [Servidor]  INFO en net.minecraft.server.v1_12_R1.MinecraftServer.D (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Server]  INFO en la fuente .bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat (CraftScheduler.java:353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24,06 19:31:45  [Server]  INFO en org.bukkit.craftbukkit .v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Server]  INFO en me.egg82.ae.tasks. TaskCalling.run (TaskCalling.java:50) ~ [?:?]
 24.06 19:31:45  [Server]  INFOat me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ~ [?:?]
 24.06 19:31:45  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> BukkitEnchantableItem.java:33) ~ [:??]
 24.06 19:31:45  [servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [:??]
 24.06 19: 31:45  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:45  [Server]  INFO java.lang.NoSuchMethodError: org. bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:45  [Servidor]  WARNLa tarea # 1280577 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:45  [Server]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8.0_181]
 24.06 19:31:45  [ Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Servidor]  INFO en la red. minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Server]  INFO en net.minecraft.server.v1_12_R1. DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45 [Servidor]  INFO en net.minecraft.server.v1_12_R1.MinecraftServer.D (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Server]  INFO en la fuente .bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat (CraftScheduler.java:353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24,06 19:31:45  [Server]  INFO en org.bukkit.craftbukkit .v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:45  [Server]  INFO en me.egg82.ae.tasks. TaskWither.run (TaskWither.java:46) ~ [?:?]
 24.06 19:31:45  [Server]  INFOat me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ~ [?:?]
 24.06 19:31:45  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> BukkitEnchantableItem.java:33) ~ [:??]
 24.06 19:31:45  [servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [:??]
 24.06 19: 31:45  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:45  [Server]  INFO java.lang.NoSuchMethodError: org. bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:45  [Servidor]  WARNLa tarea # 1280576 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:45  [Multicraft] Se omitieron 138 líneas debido al límite de velocidad (30 / s)
24.06 19:31:44  [Servidor]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:44  [Servidor]  WARN La tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:44  [Servidor]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8 .0_181]
 24.06 19:31:44  [Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19: 31:44  [Servidor]  INFOat net.minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Server]  INFO at net.minecraft.erver .v1_12_R1.DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Server]  INFO en net.minecraft.server.v1_12_R1.MinecraftServerD (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Servidor]  INFO en org.bukkit.craftbukkpázpáz : 353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Servidor]  INFOat org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Servidor]  INFO en mí. egg82.ae.tasks.TaskRepairing.run (TaskRepairing.java:41) ~ [?:?]
 24.06 19:31:44  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java) ) ~ [?:?]
 24.06 19:31:44  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> (BukkitEnchantableItem.java:33) ~ [?:?]
 24.06 19:31:44  [Servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [?:?]
 24.06 19:31:44  [Servidor] INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:44  [Server]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantment.Enchantment. getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:44  [Servidor]  WARN La tarea # 1280575 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:44  [Servidor]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8 .0_181]
 24.06 19:31:44  [Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19: 31:44  [Servidor]  INFOat net.minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Server]  INFO at net.minecraft.erver .v1_12_R1.DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Server]  INFO en net.minecraft.server.v1_12_R1.MinecraftServerD (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Servidor]  INFO en org.bukkit.craftbukkpázpáz : 353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Servidor]  INFOat org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:44  [Servidor]  INFO en mí. egg82.ae.tasks.TaskMagnetic.run (TaskMagnetic.java:36) ~ [?:?]
 24.06 19:31:44  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ) ~ [?:?]
 24.06 19:31:44  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> (BukkitEnchantableItem.java:33) ~ [?:?]
 24.06 19:31:44  [Servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [?:?]
 24.06 19:31:44  [Servidor] INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:44  [Server]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantment.Enchantment. getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:44  [Servidor] La  tarea de WARN # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:44  [ Multiactividad ] Se omitieron 152 líneas debido al límite de velocidad (30 / s)
 24.06 19:31:43  [Servidor ]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:43  [Servidor]  WARNLa tarea # 1280576 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:43  [Server]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8.0_181]
 24.06 19:31:43  [ Servidor]  INFO en net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Servidor]  INFO en la red. minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Server]  INFO en net.minecraft.server.v1_12_R1. DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43 [Servidor]  INFO en net.minecraft.server.v1_12_R1.MinecraftServer.D (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Server]  INFO en la fuente .bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat (CraftScheduler.java:353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24,06 19:31:43  [Server]  INFO en org.bukkit.craftbukkit .v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Server]  INFO en me.egg82.ae.tasks. TaskMagnetic.run (TaskMagnetic.java:36) ~ [?:?]
 24.06 19:31:43  [Server]  INFOat me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ~ [?:?]
 24.06 19:31:43  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> BukkitEnchantableItem.java:33) ~ [:??]
 24.06 19:31:43  [servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [:??]
 24.06 19: 31:43  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:43  [Server]  INFO java.lang.NoSuchMethodError: org. bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:43  [Servidor]  WARNLa tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:43  [Server]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8.0_181]
 24.06 19:31:43  [ Servidor]  INFO en net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Servidor]  INFO en la red. minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Server]  INFO en net.minecraft.server.v1_12_R1. DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43 [Servidor]  INFO en net.minecraft.server.v1_12_R1.MinecraftServer.D (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Server]  INFO en la fuente .bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat (CraftScheduler.java:353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24,06 19:31:43  [Server]  INFO en org.bukkit.craftbukkit .v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:43  [Server]  INFO en me.egg82.ae.tasks. TaskMagnetic.run (TaskMagnetic.java:36) ~ [?:?]
 24.06 19:31:43  [Server]  INFOat me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ~ [?:?]
 24.06 19:31:43  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> BukkitEnchantableItem.java:33) ~ [:??]
 24.06 19:31:43  [servidor]  INFO en me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [:??]
 24.06 19: 31:43  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:43  [Server]  INFO java.lang.NoSuchMethodError: org. bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:43  [Servidor]  WARNLa tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:43  [Multicraft] Se omitieron 110 líneas debido al límite de velocidad (30 / s)
24.06 19:31:42  [Servidor]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:42  [Servidor]  WARN La tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:42  [Servidor]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8 .0_181]
 24.06 19:31:42  [Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19: 31:42  [Servidor]  INFOat net.minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Server]  INFO at net.minecraft.erver .v1_12_R1.DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Server]  INFO en net.minecraft.server.v1_12_R1.MinecraftServerD (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Servidor]  INFO en org.bukkit.craftbukkpázpázpáceo de los niños : 353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Servidor]  INFOat org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Servidor]  INFO en mí. egg82.ae.tasks.TaskMagnetic.run (TaskMagnetic.java:36) ~ [?:?]
 24.06 19:31:42  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ) ~ [?:?]
 24.06 19:31:42  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> (BukkitEnchantableItem.java:33) ~ [?:?]
 24.06 19:31:42  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [?:?]
 24.06 19:31:42  [Servidor] INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:42  [Server]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantment.Enchantment. getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:42  [Servidor]  WARN La tarea # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:42  [Servidor]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8 .0_181]
 24.06 19:31:42  [Servidor]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19: 31:42  [Servidor]  INFOat net.minecraft.server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Server]  INFO at net.minecraft.erver .v1_12_R1.DedicatedServer.D (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Server]  INFO en net.minecraft.server.v1_12_R1.MinecraftServerD (MinecraftServer.java:739) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Servidor]  INFO en org.bukkit.craftbukkpázpázpáceo de los niños : 353) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Servidor]  INFOat org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run (CraftTask.java:71) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 24.06 19:31:42  [Servidor]  INFO en mí. egg82.ae.tasks.TaskMagnetic.run (TaskMagnetic.java:36) ~ [?:?]
 24.06 19:31:42  [Server]  INFO at me.egg82.ae.api.BukkitEnchantableItem.fromItemStack (BukkitEnchantableItem.java:24) ) ~ [?:?]
 24.06 19:31:42  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantableItem. <init> (BukkitEnchantableItem.java:33) ~ [?:?]
 24.06 19:31:42  [Servidor]  INFO at me.egg82.ae.api.BukkitEnchantableItem.getBukkitEnchantments (BukkitEnchantableItem.java:56) ~ [?:?]
 24.06 19:31:42  [Servidor] INFO at me.egg82.ae.api.BukkitEnchantment.fromEnchant (BukkitEnchantment.java:18) ~ [?:?]
 24.06 19:31:42  [Server]  INFO java.lang.NoSuchMethodError: org.bukkit.enchantment.Enchantment. getKey () Lorg / bukkit / NamespacedKey;
24.06 19:31:42  [Servidor] La  tarea WARN # 1280574 para AdvancedEnchantments v4.8.9 generó una excepción
 24.06 19:31:42  [Multicraft] Se omitieron 152 líneas debido al límite de velocidad (30 / s)

**Comment by egg82** [comment]
Fixed in the latest version. Enjoy!
