### ISSUE TITLE
Plugin not loading on 1.8.8

### ISSUE THREAD

**Issue by Glxde** [egg82/AdvancedEnchantments#20]
Plugin version: '4.18.23'
Server type: 'Spigot, Paper, CraftBukkit, etc....'
Server version: 'PaperSpigot 1.8.8'

**Describe the bug**
The explosive and smelt enchant is not working for me.

**To Reproduce**
1. Install the plugin
2. Start the server
3. Click on '....'
07.11 18:51:25 [Server] ERROR Error occurred while enabling AdvancedEnchantments v4.18.23 (Is it up to date?)
07.11 18:51:25 [Server] INFO java.lang.RuntimeException: Could not invoke onEnable.
07.11 18:51:25 [Server] INFO at me.egg82.ae.BukkitBootstrap.onEnable(BukkitBootstrap.java:82) ~[?:?]
07.11 18:51:25 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [paperspigot1.8.8.jar:git-PaperSpigot-881dfe0-de5c261]
07.11 18:51:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

**Screenshots**
https://gyazo.com/0e31c5d09b3915028a5b040a6177dc3f

**Additional context**

**Comment by egg82** [comment]
Looks an issue with the plugin not loading at all. Although I don't have a full stacktrace in the report, I have a hunch as to why.
Try the latest build at https://jenkins.egg82.me/job/egg82/job/AdvancedEnchantments/job/master/
If that works, feel free to close.
