### ISSUE TITLE
4.20.26 bugs

### ISSUE THREAD

**Issue by HexaMark** [egg82/AdvancedEnchantments#28]
Plugin version: '4.20.26'
Server type: 'Paper-237'
Server version: '1.15.2'

Describe the bug
In 4.20.26, sometimes enchanting an item will not make the "item enchanted sound", will apply a custom enchant and then take 30 levels from the player (Even though that's not possible in modern Minecraft). Enchantments have no weight (that means u can have 20 enchantments on one item). Enchantments bypass Factions plugin. (For example, u can kill your ally while using a weapon that has bleeding, thunderous or poisonous). Its impossible to get advanced enchantments on a bow.

Expected behavior
I expect the plugin to work

To Reproduce
Combine enchanted items and try enchanting items via enchantment table

Plugins
AdvancedEnchantments, AdvancedGift, AdvancedPortals, AsyncWorldEdit, AuctionHouse, AutoSaveWorld, BigDoors, Citizens, CitizensCMD, ClearLag, ColoredSigns, CoreProtect, CraftingStore, CustomGUI, DeadChest, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, Factions, FastAsyncWorldEdit, GCore, HolographicDisplays, JupiterCore, LagAssist, LimitPillagers, LuckPerms, MaintenanceSpigot, MassiveCore, McCombatLevel, mcMMO, MorphRedeem, MovingDevApi, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, NoFireworkDamage, NoPhantoms, NoteBlockAPI, PlaceholderAPI, PluginConstructorAPI, ProPackages, ProtocolLib, PVPControl, RandomTeleport, SAML, Scoreboard-revision, Sentinel, ServerRestorer, SharpnessDamageIncreaser, ShopGUIPlus, sleep-most, SlotMachineGUI, SpecializedCrates, SuperVanish, TAB, TokenManager, UltimateAutoRestart, Vault, ViaVersion, VillagerOptimiser, VoidGenerator, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, XPBoost

Screenshots/Video
None

Additional context
None

**Comment by egg82** [comment]
Enchantments being able to stack indefinitely is a feature, not a bug. (for now)
If you want to see this change, a feature request would be appreciated!

**Comment by egg82** [comment]
I wasn't able to reproduce the bow issue. Otherwise, 4.20.27 should fix everything here.
