### ISSUE TITLE
Can't download maven jars

### ISSUE THREAD

**Issue by solonovamax** [egg82/AdvancedEnchantments#29]
Plugin version: Latest git commit
Maven version: Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root) and Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00).
Java version: run on both 11 and 12.

**Describe the bug**
The dependencies for the project cannot be resolved.

**Expected behaviour**
It actually downloads the dependencies.

**To Reproduce**
1. git clone the repo
2. run `mvn install`

I ran it on 2 separate computers and both of them threw the same error. One was a manjaro (arch linux) install and the other was a windows install.

Error message:
```
[ERROR] Failed to execute goal on project advancedenchantments-bukkit: Could not resolve dependencies for project me.egg82:advancedenchantments-bukkit:jar:4.20.27: Failed to collect dependencies at com.destroystokyo.paper:paper-api:jar:1.15.1-R0.1-SNAPSHOT -> net.md-5:bungeecord-chat:jar:1.13-SNAPSHOT: Failed to read artifact descriptor for net.md-5:bungeecord-chat:jar:1.13-SNAPSHOT: Could not transfer artifact net.md-5:bungeecord-parent:pom:1.13-20190422.195939-129 from/to CodeMC-proxy (https://nexus.egg82.me/repository/codemc/): Transfer failed for https://nexus.egg82.me/repository/codemc/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-20190422.195939-129.pom 502 Bad Gateway -> [Help 1]
```

Full error log here: https://pastebin.com/zpVzPN7a

**Comment by egg82** [comment]
Going to the URL listed (https://nexus.egg82.me/repository/codemc/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-20190422.195939-129.pom) it seems to be returning a 200 response. Additionally, I can build it fine on my PC and on my Jenkins. I restarted the nexus server for updates a while ago, so maybe try it again.

Otherwise, issue seems resolved.

**Comment by solonovamax** [comment]
I think it passed the bungeecord parent lib, but it is not running into a 502 at `https://nexus.egg82.me/repository/dmulloy2/me/egg82/advancedenchantments-common/4.20.27/advancedenchantments-common-4.20.27.pom`.

Error code here:
```
Failed to execute goal on project advancedenchantments-bukkit: Could not resolve dependencies for project me.egg82:advancedenchantments-bukkit:jar:4.20.27: Failed to collect dependencies at me.egg82:advancedenchantments-common:jar:4.20.27: Failed to read artifact descriptor for me.egg82:advancedenchantments-common:jar:4.20.27: Could not transfer artifact me.egg82:advancedenchantments-common:pom:4.20.27 from/to dmulloy2-repo-proxy (https://nexus.egg82.me/repository/dmulloy2/): Transfer failed for https://nexus.egg82.me/repository/dmulloy2/me/egg82/advancedenchantments-common/4.20.27/advancedenchantments-common-4.20.27.pom 502 Bad Gateway
```

**Comment by egg82** [comment]
Really strange that it's failing on that for you, but once again I've checked on my end and on Jenkins and it seems to build fine. Jenkins's Maven cache is cleared once a day to ensure proper builds.

Not sure, sorry.

**Comment by solonovamax** [comment]
I'll try doing it again when I get to my pc. Hopefully, this is an issue that time has fixed.
