### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by g3ra456** [egg82/AdvancedEnchantments#4]
tiene error en la consola este plugin 
02.07 15:26:44  [Servidor]  ERROR No se pudo pase el evento EntityDeathEvent a AdvancedEnchantments v4.10.12 02.07
 15:26:44  [Server]  INFO en java.lang.Thread.run (Thread.java:748) [?: 1.8.0_181]
 02.07 15:26:44  [Server]  INFOat net.minecraft.server.v1_12_R1.MinecraftServer.run (MinecraftServer.java:577) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Server]  INFO en net.minecraft.server .v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFO at net.minecraft.server.v1_12_R1.DedicatedServerD (DedicatedServer.java:406) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFO en net.minecraft.server.v1_12_R1.MinecraftServer.D (MinecraftServer.java:748 ) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFOat net.minecraft.server.v1_12_R1.SystemUtils.a (SourceFile: 46) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Server]  INFO en java.util.concurrent.FutureTask .run (FutureTask.java:266) [?: 1.8.0_181]
 02.07 15:26:44  [Server]  INFO at java.util.concurrent.Executors $ RunnableAdapter.call (Executors.java:511) [?: 1.8. 0_181] 02.07
 15:26:44  [Servidor]  INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils $ 1.run (SourceFile: 13) [spigot1.12.2.jar: git-Spigot-7754231-94b0980] 02.07
 15:26: 44  [Servidor]  INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a (SourceFile: 13) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
02.07 15:26:44  [Servidor]  INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a (SourceFile: 69) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor ]  INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a (PlayerConnection.java:1616) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFO at net.minecraft .server.v1_12_R1.EntityPlayer.attack (EntityPlayer.java:1302) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Server]  INFO en net.minecraft.server.v1_12_R1.Entity .attack (EntityHuman.java:1005) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor] INFO at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity (EntityZombie.java:163) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFO en net.minecraft. server.v1_12_R1.EntityMonster.damageEntity (EntityMonster.java:44) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Server]  INFO en net.minecraft.server.v1_12_R1.Entline. damageEntity (EntityLiving.java:951) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Server]  INFO en net.minecraft.server.v1_12_R1.EntityZombie.die (EntityZombie.java: 429) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFOat net.minecraft.server.v1_12_R1.EntityLiving.die (EntityLiving.java:1109) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Server]  INFO en org.bukkit.craftbukkit .v1_12_R1.event.CraftEventFactory.callEntityDeathEvent (CraftEventFactory.java:394) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02,07 15:26:44  [Server]  INFO en org.bukkit.plugin.SimplePluginManager.callEvent (SimplePluginManager.java:484) [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Server]  INFO en org.bukkit.plugin.SimplePluginManager.fireEvent (SimplePluginManager.java.4ava spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFOat org.bukkit.plugin.RegisteredListener.callEvent (RegisteredListener.java:62) ~ [spigot1.12.2.jar: git-Spigot-7754231-94b0980]
 02.07 15:26:44  [Servidor]  INFO at ninja.egg82.events. BukkitEventSubscriber.lambda $ new $ 0 (BukkitEventSubscriber.java:31) ~ [?:?]
 02.07 15:26:44  [Servidor]  INFO at ninja.egg82.events.BukkitEventSubscriber.call (BukkitEventSubscriber.pe? ?]
 02.07 15:26:44  [Servidor]  INFO at ninja.egg82.events.SingleEventSubscriber.call (SingleEventSubscriber.java:90) ~ [?:?]
 02.07 15:26:44  [Server]  INFO at ninja.egg82. events.SingleEventSubscriber.filter (SingleEventSubscriber.java:166) ~ [?:?]
 02.07 15:26:44 [Servidor]  INFO java.lang.ClassCastException: org.bukkit.event.entity.EntityDeathEvent no se puede convertir en org.bukkit.event.Cancellable
 02.07 15:26:44  [Server]  ERROR No se puede pasar el evento EntityDeathEvent a AdvancedEnchantments v4.10.12

**Comment by egg82** [comment]
Thanks for the report!
