### ISSUE TITLE
AE Enchant

### ISSUE THREAD

**Issue by Lukebix** [egg82/AdvancedEnchantments#5]
When I do the command "/ae enchant Bleeding 5" or any other enchant I get the error "i'm sorry, but there was an error preforming this command" What would be a way to fix this?

**Comment by egg82** [comment]
I'm going to need more than that to diagnose the issue.

What game version? 1.14.3? 1.8.8? 1.10? 1.12.2?
What server type? CraftBukkit? Spigot? Paper?

What does the console spit out when that happens?

**Comment by egg82** [comment]
It's possible this was a 1.8 issue and fixed in 552a67e42de43c00737e86ac78289b43babfac4d
