### ISSUE TITLE
Towny doesn't restrict custom enchantments.

### ISSUE THREAD

**Issue by BluLightShow** [egg82/AdvancedEnchantments#8]
Towny is able to restrict PVP in users' towns but even if PVP is restricted in users' towns they can still use custom enchantments on swords to hit each other, a prime example being using the tornado enchantment even if PVP is disabled. The sword won't register the hit but it will still execute the tornado effect.

**Comment by egg82** [comment]
Looks like Towny handles and cancels events on HIGH/HIGHEST instead of LOW/LOWEST priority, which would cause issues with a lot of plugins (not just mine) listening for events on lower priorities such as NORMAL.

Fixed with this PR to Towny: https://github.com/TownyAdvanced/Towny/pull/3329

**Comment by egg82** [comment]
Re-opening because apparently Towny's priorities are a hack for WG's priorities, so now I get to add in a hack for this plugin.

Plugins are lovely.

**Comment by BluLightShow** [comment]
Just read the thread, that's unfortunate they needed to use that priority just for worldguard. Thanks for the quick support and dive into the issue, your plugin's great!
